title: Kumar Atul | Performance Marketing Consultant
email: hello@kumaratul.com
description: >-
  I Help Businesses Turn Traffic Into Qualified Leads & Scalable Systems. 
  Expert Google Ads, Meta Ads, and Marketing Automation.
baseurl: "/kumaratul"
url: "https://Atulscript.github.io"

# Build settings
# remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Sass settings
sass:
  style: compressed

# Exclusion
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
